version: '3'
services:
  elasticsearch0:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    container_name: es-cluster-node0
    environment:
      - cluster.name=local-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    container_name: es-cluster-kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es-cluster-node0:9200/
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata0:
    driver: local

networks:
  esnet:
